### ISSUE TITLE
Missing aws-secrets.yaml creation step

### ISSUE THREAD

**Issue by sripathivenky** [samos123/multi-cloud-messaging#1]
Very interesting and helpful tutorial, I am new to SNS and PUB/SUB found this very helpful. I am puzzled at the publish to gcp step where the command looks for aws-secrets.yaml. Can you please point to step how to create or a template to create this.

**Comment by samos123** [comment]
It's literally environment variables defined in a YAML file that contains your AWS credentials. So for example this could be the content of `aws-secrets.yaml`:
```
AWS_ACCESS_KEY_ID: replacewithyourkey
AWS_SECRET_ACCESS_KEY: replacewithyourkey
```

For more context, see https://cloud.google.com/functions/docs/env-var and https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables
